stages:
  - build
  - deploy

variables:
  PROJECT_NAME: $CI_PROJECT_NAME
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  DEFAULT_DEPLOY_ENV: ""

build_docker_image:
  stage: build
  only:
    refs:
      - /^test.*$/
    variables:
      - $push_env !~ /test*/
  tags:
    - dev-runner-3.98
  script:
    - npm config set registry https://registry.npm.taobao.org && npm install && npm run build
    - ls | grep -E -v '(dist|Dockerfile|.gitlab-ci.yml)' | xargs rm -rf
    - export IMAGE_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g')
    - build-docker-image

deploy_to_k8s:
  stage: deploy
  only:
    - /^test.*$/
  tags:
    - dev-runner-3.98
  script:
    - export IMAGE_TAG=$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g')
    - deploy-to-k8s
  after_script:
    - echo "current push env:${push_env} image_tag:${IMAGE_TAG}"